Arte-Arena/space-frontend

modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminCostsTab.tsx
Tela de configurações do superadmin.
=> feat: Implemente a config no superadmin

modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminPermissionsTabSubTabsPapeis.tsx
Adicionado o update e o delete no front.
=> feat: Add update and delete

modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminPermissionsTabSubTabsModulos.tsx
Adicionado o Update e Delete do Modules.
=> feat: Add Update e Delete Modules

modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminPermissionsTabSubTabsModulos.tsx
=> feat: Actual front update module

modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminCostsTab.tsx
=> fix: Update custo imposto

modernize/src/app/(DashboardLayout)/apps/custo-bandeira/page.tsx
=> fix: Update endpoint at custo-bandeira

modernize/src/app/(DashboardLayout)/apps/custo-bandeira/page.tsx
=> fix: Correct bandeira cost calc

modernize/src/app/(DashboardLayout)/apps/custo-bandeira/page.tsx, modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminCostsTab.tsx
=> fix: Correct bandeira cost calc (input)

modernize/src/app/(DashboardLayout)/apps/custo-bandeira/page.tsx, modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminCostsTab.tsx
Allow int values and adjust CustoBandeira calc formula
=> feat: Allow 0-100% imposto field

modernize/src/app/(DashboardLayout)/apps/contas-pagar-receber/adicionar/page.tsx, modernize/src/app/(DashboardLayout)/apps/contas-pagar-receber/buscar/page.tsx
Adicionado o select das opções e conectado o backend
=> feat: Add select and backend

modernize/src/app/(DashboardLayout)/layout.tsx
=> feat: Change Modernize title to Spae

.gitignore, modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx, modernize/src/utils/avancarDias.ts, modernize/src/utils/brazilTime.ts, modernize/src/utils/contarFeriados.ts, modernize/src/utils/contarFinaisDeSemana.ts, modernize/src/utils/encontrarProximoDiaUtil.ts, modernize/src/utils/gerarNumeroAleatorio4Digitos.ts
Corrige o cálculo de previsão de entrega.
=> feat: Improve delibery estimation deadline

modernize/src/utils/contarFeriados.ts
=> fix: Update URL Endpoint (feriados)

modernize/src/utils/contarFeriados.ts
Define dinamicamente o bearer token
=> fix: Update URL Endpoint (feriados) (2)

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
Adiciona a função copiar orçamento.
=> feat: Add clipboard button effect

.github/workflows/ci.yml, modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
Melhora previsão de entrega e adiciona funcionalidade de copiar orçamento.
=> Copy Budget

.github/workflows/ci.yml
=> new pipeline

modernize/package-lock.json, modernize/package.json, modernize/src/app/(DashboardLayout)/apps/orcamento/backoffice/cliente-cadastro/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/backoffice/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx, modernize/src/utils/exportarPDF.ts
=> feat: Add backoffice

modernize/src/app/(DashboardLayout)/apps/orcamento/custo-bandeira/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/preco-bandeira/page.tsx, modernize/src/utils/contarFeriados.ts
feat: Remove metros change for centimetros (custo-bandeira)
=> feat: Remove metros change for centimetros (custo-bandeira)

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
quando for retirada, somente no dia posterior aos dias úteis do prazo de produção
=> feat: Add 1 day on RETIRADA frete

modernize/src/app/(DashboardLayout)/apps/orcamento/preco-bandeira/page.tsx, modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminBackupTab.tsx, modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminConfigsTabs.tsx, modernize/src/app/components/apps/userprofile/profile/ProfileBanner.tsx
Add botões de copiar na tela de Preço de Bandeiras
=> Preço de Bandeiras (copiar botões)

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page copy.tsx.bak, modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/funil/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/orcamentos-entrega/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/page.tsx, modernize/src/utils/calcDiasUteis.ts, modernize/src/utils/contarFeriados copy.ts.bak, modernize/src/utils/contarFeriados.ts, modernize/src/utils/contarFinaisDeSemana copy.ts.bak, modernize/src/utils/contarFinaisDeSemana.ts
Cria a página Orcamento Entrega
=> Leandro orcamento entrega

modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/orcamentos-nao-aprovados/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/quantidade-orcamentos-por-data/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/quantidade-orcamentos-por-status/page.tsx, modernize/src/app/components/charts/quantidadeOrcamentoChart.tsx, modernize/src/app/components/charts/quantidadeOrcamentoStatus.tsx
=> feat: add new views for charts; orcamento Por-data, Por-Status

modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/orcamentos-todos/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/page.tsx, modernize/src/app/components/DataGridFilters/CustomDataGridFilters.tsx
feat: add multi filters for the new datagrid
=> feat: add multi filters for the new datagrid

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx, modernize/src/utils/calcDiasUteis.ts
fix: prazoProducaoAntecipado improved
=> fix: prazoProducaoAntecipado improved

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
=> Desconto and Total

modernize/package-lock.json, modernize/package.json, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/orcamentos-nao-aprovados/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/orcamentos-todos/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/page.tsx, modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/quantidade-orcamentos-por-data-filtrada/page.tsx, modernize/src/app/components/DataGridFilters/CustomDataGridFilters.tsx
Chart filtered (multi-filters)
=> Chart filtered (multi-filters)

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
feat: Disable prazo and price (Brinde)
=> feat: Disable prazo and price (Brinde)

modernize/src/app/(DashboardLayout)/apps/vendas/relatorios/quantidade-orcamentos-por-data-filtrada/page.tsx, modernize/src/app/components/charts/SelectUsers.tsx
Gustavo chart filtered, new charts filter: nome dos vendedores
=> Gustavo chart filtered

modernize/src/utils/formatarPDF.ts
=> fix: fix formatarPDF

modernize/src/utils/formatarPDF.ts
=> orcamento PDF

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
feat: Try memoized all clients
=> feat: Try memoized all clients

modernize/src/app/(DashboardLayout)/apps/orcamento/buscar/page.tsx, modernize/src/utils/PutStatusOrcamentos.tsx
add new buttons and handle for change the status
=> add new buttons and handle for change the status

modernize/src/app/(DashboardLayout)/apps/orcamento/buscar/page.tsx
feat: add new logic to the handle desaprovar
=> feat: add new logic to the handle desaprovar

modernize/src/utils/formatarPDF.ts
=> Gustavo refatorar pdf

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx, modernize/src/app/layout.tsx, modernize/src/utils/BackgroundUpdater.tsx
feat: Optimize Cliente and Products Fields on Gerar Orcamento
=> feat: Optimize Cliente and Products Fields on Gerar Orcamento

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
fix: Remove 5 seconds from test delay
=> fix: Remove 5 seconds from test delay

modernize/src/utils/formatarPDF.ts
fix: numeros do cabecalho deletados
=> fix: numeros do cabecalho deletados

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx, modernize/src/utils/formatarPDF.ts
Remove 5 seconds test and Fix PDF format
=> Remove 5 seconds test and Fix PDF format

modernize/src/app/(DashboardLayout)/apps/orcamento/editar/[id]/page.tsx
=> add edit orcamentos page

modernize/src/app/(DashboardLayout)/apps/orcamento/editar/page.tsx, modernize/src/utils/BackgroundUpdater.tsx
feat: Add general list page for Budget Edit
=> feat: Add general list page for Budget Edit

modernize/src/app/(DashboardLayout)/apps/orcamento/status/page.tsx, modernize/src/app/(DashboardLayout)/layout/vertical/sidebar/MenuItems.ts, modernize/src/utils/useThemeMode.ts
feat: add new pages and route for orçamento status and orçamento buscar
=> feat: add new pages and route for orçamento status and orçamento buscar

modernize/src/app/(DashboardLayout)/apps/orcamento/editar/page.tsx
feat: add new link button to the editar oramento plus ID
=> feat: add new link button to the editar oramento plus ID

modernize/src/app/(DashboardLayout)/apps/orcamento/editar/[id]/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/editar/page.tsx
=> Link para editar orçamento

modernize/src/app/(DashboardLayout)/apps/orcamento/buscar/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/editar/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/status/page.tsx, modernize/src/app/(DashboardLayout)/layout/vertical/sidebar/MenuItems.ts
feat: add new interface orcamentos, fix the formatation of the last row, fix the icon buttuns and the handle to the rigth page
=> feat: add new interface orcamentos, fix the formatation of the last row, fix the icon buttuns and the handle to the rigth page

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
feat: Reset frete states when new cep input fails
=> feat: Reset frete states when new cep input fails

modernize/src/app/u/[code]/page.tsx, modernize/src/utils/useFetch.ts
=> Pablo add uniforms screen

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
feat: Add client search on blur Client Field text input
=> feat: Add client search on blur Client Field text input

modernize/src/app/(DashboardLayout)/apps/orcamento/backoffice/cliente-cadastro/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/backoffice/cliente-cadastro/sucesso/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/backoffice/page.tsx, modernize/src/app/components/apps/chats/ChatContent.tsx, modernize/src/app/components/apps/contacts/ContactDetails.tsx, modernize/src/app/components/apps/contacts/ContactFilter.tsx, modernize/src/app/components/apps/contacts/ContactList.tsx, modernize/src/app/components/apps/ecommerce/productDetail/ProductDesc.tsx, modernize/src/app/components/apps/email/EmailCompose.tsx, modernize/src/app/components/apps/email/EmailFilter.tsx, modernize/src/app/components/apps/email/EmailList.tsx, modernize/src/app/components/apps/email/EmailListItem.tsx, modernize/src/app/components/apps/userprofile/followers/FollowerCard.tsx, modernize/src/app/components/apps/userprofile/friends/FriendsCard.tsx, modernize/src/app/components/apps/userprofile/gallery/GalleryCard.tsx, modernize/src/app/components/apps/userprofile/profile/IntroCard.tsx, modernize/src/app/components/apps/userprofile/profile/PhotosCard.tsx, modernize/src/app/components/apps/userprofile/profile/PostTextBox.tsx, modernize/src/utils/i18n.ts, package-lock.json
feat: add new handle to post data for pedidos in tiny api
=> feat: add new handle to post data for pedidos in tiny api

modernize/src/app/(DashboardLayout)/apps/vendas/crm/page.tsx, modernize/src/app/(DashboardLayout)/layout/vertical/sidebar/MenuItems.ts
Add Catalogo 2025 and update CRM
Organize menu items
=> Leandro catalogo crm

modernize/src/app/(DashboardLayout)/apps/orcamento/aprovar/[id]/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/aprovar/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/page.tsx, modernize/src/app/(DashboardLayout)/layout/vertical/sidebar/MenuItems.ts
=> orcamentos aprovar

modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/types.tsx
=> feat: Edit Pacotes

modernize/src/app/(DashboardLayout)/apps/orcamento/backoffice/page.tsx
Feat: add new validation for the button and dinamic loading with useEffect
=> Feat: add new validation for the button and dinamic loading with useEffect

modernize/src/app/(DashboardLayout)/apps/orcamento/editar/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/page.tsx, modernize/src/app/(DashboardLayout)/layout/vertical/sidebar/MenuItems.ts, modernize/src/app/(DashboardLayout)/layout/vertical/sidebar/NavItem/index.tsx
"fix: Correct produtos pacotes menu itens"
=> "fix: Correct produtos pacotes menu itens"

modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/ProdutoPacoteUniformeForm.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/[id]/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/add/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/edit/[id]/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/types.tsx
feat: Add Editar and Deletar button to Pacotes Uniformes's Form
=> feat: Add Editar and Deletar button to Pacotes Uniformes's Form

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
Add prazo_producao to GerarOrcamentoScreen
=> Add prazo_producao to GerarOrcamentoScreen

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
fix: Add Lalamove to shippingOption prazo and preco states
=> fix: Add Lalamove to shippingOption prazo and preco states

modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/add/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/edit/[id]/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/page.tsx
feat: Implement loading to all buttons on Pacotes Uniformes
=> feat: Implement loading to all buttons on Pacotes Uniformes

modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/add/page.tsx, modernize/src/app/(DashboardLayout)/apps/produtos/pacotes-uniformes/edit/[id]/page.tsx
feat: Add api fetch to pacotes-uniformes add and edit screens
=> feat: Add api fetch to pacotes-uniformes add and edit screens

modernize/src/app/(DashboardLayout)/apps/orcamento/backoffice/cliente-cadastro/page.tsx, modernize/src/app/s/[code]/page.tsx
fix: Remove accessToken from cliente-cadastro
=> fix: Remove accessToken from cliente-cadastro

modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx
feat: Add loading on Clientes autocomplete input (gerar orcamento)
=> feat: Add loading on Clientes autocomplete input (gerar orcamento)

modernize/src/app/(DashboardLayout)/apps/producao/arte-final/[id]/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/edit/page.tsx
feat: Add octadesk test screen (2)
=> feat: Add octadesk test screen (2)

modernize/src/app/(DashboardLayout)/apps/chats/chat-externo/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/ArteFinalForm.tsx, modernize/src/app/(DashboardLayout)/layout/vertical/sidebar/MenuItems.ts
feat: Add logic to productsList on ArteFinal
=> feat: Add logic to productsList on ArteFinal

modernize/src/app/(DashboardLayout)/apps/orcamento/editar/[id]/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/ArteFinalForm.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/add/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/types.tsx, modernize/src/utils/BackgroundUpdater.tsx
=> Add onSubmit to ArteFinalForm

modernize/src/app/(DashboardLayout)/apps/producao/arte-final/ArteFinalForm.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/edit/[id]/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/types.tsx, modernize/src/utils/BackgroundUpdater.tsx
feat: Create ArteFinal updates
=> feat: Create ArteFinal updates

modernize/src/app/(DashboardLayout)/apps/producao/arte-final/ArteFinalForm.tsx
sec: Add vaidation to confirm right existence of list_produtos
=> sec: Add vaidation to confirm right existence of list_produtos

modernize/src/app/(DashboardLayout)/apps/producao/arte-final/ArteFinalForm.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/edit/[id]/page.tsx
feat: Add block_tiny to Edit and ArteFinalForm
=> feat: Add block_tiny to Edit and ArteFinalForm

modernize/src/app/(DashboardLayout)/apps/producao/arte-final/ArteFinalForm.tsx
feat: Add loading to ArteFinalForm Button
=> feat: Add loading to ArteFinalForm Button

modernize/src/app/(DashboardLayout)/apps/producao/arte-final/ArteFinalForm.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/add/page.tsx
feat: Add vendedor_id to Payload ArteFinal
=> feat: Add vendedor_id to Payload ArteFinal

modernize/src/app/(DashboardLayout)/apps/producao/arte-final/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/confeccao/components/drawer.tsx, modernize/src/app/(DashboardLayout)/apps/producao/confeccao/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/impressao/components/drawer.tsx, modernize/src/app/(DashboardLayout)/apps/producao/impressao/page.tsx
fix: Add pagination to the indexes producao
=> fix: Add pagination to the indexes producao

modernize/src/app/(DashboardLayout)/apps/orcamento/backoffice/page.tsx, modernize/src/app/(DashboardLayout)/apps/orcamento/gerar/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/ArteFinalForm.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/components/designerDialog.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/components/observacaoDialog.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/types.tsx, modernize/src/app/(DashboardLayout)/apps/producao/confeccao/components/observacaoDialog.tsx, modernize/src/app/(DashboardLayout)/apps/producao/expedicao/components/observacaoDialog.tsx, modernize/src/app/(DashboardLayout)/apps/producao/impressao/components/observacaoDialog.tsx
=> fix Pedido Arte Final

modernize/src/app/(DashboardLayout)/apps/producao/arte-final/components/useTrocarMedidaLinear.ts, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/page.tsx, modernize/src/app/(DashboardLayout)/apps/producao/impressao/components/useTrocarMedidaLinear.ts
refact: Upgrade grid align to Arte Final's Action Column
=> refact: Upgrade grid align to Arte Final's Action Column  

modernize/src/app/(DashboardLayout)/apps/producao/arte-final/components/drawer.tsx, modernize/src/app/(DashboardLayout)/apps/producao/arte-final/page.tsx, modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminTermTab.tsx, modernize/src/app/(DashboardLayout)/apps/user-profile/super-admin/SuperAdminTermTabSubTabs.tsx, modernize/src/utils/BackgroundUpdater.tsx
=> feat: Add prazoArteFinal

modernize/src/app/(DashboardLayout)/apps/producao/confeccao/corte-conferencia/page.tsx
fix: Correct moving to Costura from Corte & Conferencia
=> fix: Correct moving to Costura from Corte & Conferencia

modernize/src/utils/BackgroundUpdater.tsx
=> fix: error data homolog

modernize/src/store/apps/chat/ChatSlice.tsx
* feat: Add send message integration
* feat: add create new conta form (#500)
* feat: add create new conta form
* feat: add form and dialog in form for recorrencias
* feat: Add ws logs (#504)
* feat: Add ws logs (#506)
* Leandro chat dialog 2 (#507)
* feat: Add ws logs
* feat: Add heartbeat inside subscribeChats component
---------
=> Homolog (#508)
